### ISSUE TITLE
[BUG] Metal graphics backend does not compile on version 0.14.0

### ISSUE THREAD

**Issue by lmcgrath** [amethyst/amethyst#2132]
## Description

Enabling the `metal` feature on macos fails to compile.

## Reproduction Steps

This issue can be reproduced with the complete pong example on macos using `cargo run --features="metal"`

## Screenshots and Logs

```
➜ cargo run --features="metal"
   Compiling gfx-backend-metal v0.3.3
   Compiling metal v0.16.0
   Compiling winit v0.19.5
error: failed to run custom build command for `gfx-backend-metal v0.3.3`

Caused by:
  process didn't exit successfully: `/Users/logan/workspace/engineblock-rs/target/debug/build/gfx-backend-metal-1a38ff9f34915c58/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=/Users/logan/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.3.3/shaders
cargo:rerun-if-changed=/Users/logan/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.3.3/shaders/blit.metal

--- stderr
xcrun: error: unable to find utility "metal", not a developer tool or in PATH
thread 'main' panicked at 'shader compilation failed', /Users/logan/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.3.3/build.rs:69:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Your Environment

1. Operating System: *macos*
2. Operating System Version: *10.15.2*
3. Version of Amethyst: *0.14.0*

**Comment by lmcgrath** [comment]
Found the problem: I was running an old Xcode version. Current version works.
