### ISSUE TITLE
[BUG] Bump to 0.22.2 errors due to importing amethyst_core as core

### ISSUE THREAD

**Issue by j4qfrost** [amethyst/amethyst#2478]
## Description

I encountered an error caused by the Derivative trait essentially saying that rust core libraries aren't present in core after bumping the winit version to 0.22.2 on the wasm branch. I believe this is present regardless of the wasm changes since the engine compiles for me with 0.22.0 and for another user on 0.22.1 winit.
## Reproduction Steps

1. Bump winit version to 0.22.2
2. Make sure you are on a branch that is compatible with winit >=0.20 changes
3. Build

## What You Expected to Happen
I just wanted it to work.

## What Actually Happened

It failed with three errors.

## Screenshots and Logs
Pasted from another user since I am building on a separate machine. This is essentially the same as what I saw for my errors.
```
error[E0433]: failed to resolve: could not find fmt in core
  --> /home/shinra/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/app.rs:44:10
   |
44 | #[derive(Derivative)]
   |          ^^^^^^^^^^ could not find fmt in core
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find fmt in core
   --> /home/shinra/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/state.rs:366:10
    |
366 | #[derive(Derivative)]
    |          ^^^^^^^^^^ could not find fmt in core
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find clone in core
  --> /home/shinra/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/state_event.rs:17:17
   |
17 | #[derive(Debug, Derivative, EventReader)]
   |                 ^^^^^^^^^^ could not find clone in core
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

## Your Environment

1. Arch Linux 5.8.5-arch1-1
3. wasm with merge from upstream master #9453e966c468

## Additional Context
You can get past these errors by importing the rust core libraries through amethyst_core, but this is a hacky solution. One user on a Rust community Discord suggested sending a ticket in to the derivatives crate to reexport internals to avoid depending on amethyt crates? Still wrapping my head around that.

**Comment by Blisto91** [comment]
Adding some extra notes from discord.

[This is the offending winit commit](github.com/rust-windowing/winit/commit/b8828105cf6231e249da279851285aecd2970b4b) where this started happening.

It can be reproduced by creating an empty cargo project and adding amethyst as a dependency and also.
```
[target.'cfg(target_os = "android")'.dependencies]
ndk = "0.1.0"
ndk-sys = "0.1.0"
ndk-glue = "0.1.0"
```
These were added in the winit commit.

There might be some cargo funkyness involved since running with the ``-Z features=itarget`` nightly flag also gets rid of the error.

**Comment by interfect** [comment]
This affects me too, trying to use Amethyst as a rendering backend for RLTK:

```
[dependencies.rltk]
version = "0.8.0"
default-features = false 
features = ["amethyst_engine_vulkan"]
```

I am using:

```
cargo 1.46.0 (149022b1d 2020-07-17)
rustc 1.46.0 (04488afe3 2020-08-24)
```

And to build I am running `cargo build`.

**Comment by ezpuzz** [comment]
> This affects me too, trying to use Amethyst as a rendering backend for RLTK:
> 
> ```
> [dependencies.rltk]
> version = "0.8.0"
> default-features = false 
> features = ["amethyst_engine_vulkan"]
> ```
> 
> I am using:
> 
> ```
> cargo 1.46.0 (149022b1d 2020-07-17)
> rustc 1.46.0 (04488afe3 2020-08-24)
> ```
> 
> And to build I am running `cargo build`.

This is fixed upstream in legion_v2 branch.  We have to import std::core::fmt manually to workaround bug. https://github.com/amethyst/amethyst/blob/273a94678c46b6b4222ac8263efc6c5962a2f06d/amethyst_core/src/lib.rs#L21

**Comment by ezpuzz** [comment]
Also legion_v2 is on winit 0.24.0 and could use testing

**Comment by Connoropolous** [comment]
> Adding some extra notes from discord.
> 
> [This is the offending winit commit](https://github.com/rust-windowing/winit/commit/b8828105cf6231e249da279851285aecd2970b4b) where this started happening.
> 
> It can also be reproduced by creating an empty cargo project and adding amethyst as a dependency together with
> 
> ```
> [target.'cfg(target_os = "android")'.dependencies]
> ndk = "0.1.0"
> ndk-sys = "0.1.0"
> ndk-glue = "0.1.0"
> ```
> 
> These were added in the winit commit.
> 
> There might be some cargo funkyness involved since running with the `-Z features=itarget` nightly flag also gets rid of the error.

Using nightly plus this also worked for me: `-Z features=itarget`
but then I realized it has matured and is now `resolver = "2"` for Cargo.toml, and can be used on stable. I don't know why this fixing my very similar issue as reported here (but in a different context) but it is!
https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
